var tinyMCEImageList = new Array(
['Images: articles','http://elonbc.sytes.net/images/articles'],
['Images: avatars','http://elonbc.sytes.net/images/avatars'],
['Images: banner.gif','http://elonbc.sytes.net/images/banner.gif'],
['Images: banners','http://elonbc.sytes.net/images/banners'],
['Images: bg.jpg','http://elonbc.sytes.net/images/bg.jpg'],
['Images: edit.gif','http://elonbc.sytes.net/images/edit.gif'],
['Images: imagelist.js','http://elonbc.sytes.net/images/imagelist.js'],
['Images: imagenotfound.jpg','http://elonbc.sytes.net/images/imagenotfound.jpg'],
['Images: logo.jpg','http://elonbc.sytes.net/images/logo.jpg'],
['Images: news','http://elonbc.sytes.net/images/news'],
['Images: news-bg.jpg','http://elonbc.sytes.net/images/news-bg.jpg'],
['Images: news_cats','http://elonbc.sytes.net/images/news_cats'],
['Images: photoalbum','http://elonbc.sytes.net/images/photoalbum'],
['Images: smiley','http://elonbc.sytes.net/images/smiley'],
['Images: star.gif','http://elonbc.sytes.net/images/star.gif'],
['Images: Thumbs.db','http://elonbc.sytes.net/images/Thumbs.db'],
['Images: tick.gif','http://elonbc.sytes.net/images/tick.gif'],
['Images: validate_bg.jpg','http://elonbc.sytes.net/images/validate_bg.jpg'],
[' album: album_1','http://elonbc.sytes.net/images/photoalbum/album_1'],
[' album: album_2','http://elonbc.sytes.net/images/photoalbum/album_2'],
[' album: outland1_t1.jpg','http://elonbc.sytes.net/images/photoalbum/outland1_t1.jpg'],
[' album: submissions','http://elonbc.sytes.net/images/photoalbum/submissions'],
[' album: Thumbs.db','http://elonbc.sytes.net/images/photoalbum/Thumbs.db']);

